import { defineArrayMember, defineField, defineType } from "sanity";
import { colorOptions, craftOptions, materialOptions, typeOptions } from "../options";

export const product = defineType({
  name: "product",
  title: "Product",
  type: "document",
  groups: [
    { name: "basics", title: "Basics", default: true },
    { name: "details", title: "Details" },
    { name: "inventory", title: "Stock & Etsy" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "basics",
      description: "e.g. “Hand-embroidered Pashmina Shawl – Midnight Blue”",
      validation: (r) => r.required().max(120),
    }),
    defineField({
      name: "slug",
      title: "Web address",
      type: "slug",
      group: "basics",
      description: "Click “Generate”. This becomes the product's link.",
      options: { source: "title", maxLength: 96 },
      validation: (r) => r.required(),
    }),
    defineField({
      name: "images",
      title: "Photos",
      type: "array",
      group: "basics",
      description:
        "Drag to reorder. The first photo is the main image. Portrait (4:5) photos in natural light look best.",
      of: [
        defineArrayMember({
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({
              name: "alt",
              title: "Short description of the photo",
              type: "string",
              description: "Helps visually impaired shoppers and Google, e.g. “Navy shawl draped over shoulders”.",
              validation: (r) => r.required(),
            }),
          ],
        }),
      ],
      options: { layout: "grid" },
      validation: (r) => r.required().min(1),
    }),
    defineField({
      name: "video",
      title: "Short video (optional)",
      type: "file",
      group: "basics",
      description: "A 5–15 second clip of the piece being draped (MP4 or MOV from your iPhone). Plays silently in the gallery.",
      options: { accept: "video/mp4,video/quicktime,video/webm" },
    }),
    defineField({
      name: "price",
      title: "Price (USD)",
      type: "number",
      group: "basics",
      validation: (r) => r.required().positive().precision(2),
    }),
    defineField({
      name: "compareAtPrice",
      title: "Original price (optional)",
      type: "number",
      group: "basics",
      description: "Set this higher than Price to show a “Sale” badge.",
      validation: (r) => r.positive().precision(2),
    }),
    defineField({
      name: "productType",
      title: "Type",
      type: "string",
      group: "basics",
      options: { list: typeOptions, layout: "radio", direction: "horizontal" },
      initialValue: "shawl",
      validation: (r) => r.required(),
    }),
    defineField({
      name: "shortDescription",
      title: "Short description",
      type: "text",
      rows: 2,
      group: "basics",
      description: "One or two sentences, shown on product cards and in Google.",
      validation: (r) => r.required().max(200),
    }),
    defineField({
      name: "colors",
      title: "Colors",
      type: "array",
      group: "basics",
      of: [{ type: "string" }],
      options: { list: colorOptions, layout: "grid" },
    }),
    defineField({
      name: "material",
      title: "Material",
      type: "string",
      group: "details",
      options: { list: materialOptions },
    }),
    defineField({
      name: "craft",
      title: "Craft",
      type: "string",
      group: "details",
      description: "The traditional technique. It links the product to the Crafts guide.",
      options: { list: craftOptions },
    }),
    defineField({
      name: "origin",
      title: "Made in",
      type: "string",
      group: "details",
      description: "e.g. Srinagar, Kashmir · Varanasi, Uttar Pradesh",
    }),
    defineField({
      name: "description",
      title: "Full description",
      type: "array",
      group: "details",
      of: [{ type: "block", styles: [{ title: "Normal", value: "normal" }], lists: [{ title: "Bullet", value: "bullet" }] }],
    }),
    defineField({
      name: "dimensions",
      title: "Size",
      type: "string",
      group: "details",
      description: "e.g. 200 × 70 cm (79 × 28 in)",
    }),
    defineField({
      name: "carePreset",
      title: "Care instructions",
      type: "string",
      group: "details",
      options: {
        list: [
          { title: "Delicate (pashmina, cashmere, wool, silk)", value: "delicate" },
          { title: "Washable (cotton, modal, viscose)", value: "washable" },
          { title: "Dry clean only", value: "dryClean" },
          { title: "Write my own", value: "custom" },
        ],
        layout: "radio",
      },
      initialValue: "delicate",
    }),
    defineField({
      name: "care",
      title: "Custom care instructions",
      type: "text",
      rows: 3,
      group: "details",
      hidden: ({ parent }) => parent?.carePreset !== "custom",
    }),
    defineField({
      name: "collections",
      title: "Collections",
      type: "array",
      group: "details",
      of: [{ type: "reference", to: [{ type: "collection" }] }],
    }),
    defineField({
      name: "featured",
      title: "Feature on home page",
      type: "boolean",
      group: "details",
      initialValue: false,
    }),
    defineField({
      name: "stock",
      title: "Quantity in stock",
      type: "number",
      group: "inventory",
      description: "Leave empty if made to order. Set to 0 to show “Sold out”.",
      validation: (r) => r.integer().min(0),
    }),
    defineField({
      name: "etsyUrl",
      title: "Etsy listing link",
      type: "url",
      group: "inventory",
      description: "Paste the link to this item on Etsy. It powers the “Buy on Etsy” button.",
    }),
    defineField({
      name: "publishedAt",
      title: "Listed on",
      type: "datetime",
      group: "inventory",
      description: "Used for “New arrivals” sorting. Products from the last 21 days get a “New” badge.",
      initialValue: () => new Date().toISOString(),
    }),
    defineField({
      name: "seoTitle",
      title: "Google title (optional)",
      type: "string",
      group: "seo",
      validation: (r) => r.max(70),
    }),
    defineField({
      name: "seoDescription",
      title: "Google description (optional)",
      type: "text",
      rows: 2,
      group: "seo",
      validation: (r) => r.max(160),
    }),
  ],
  orderings: [
    { title: "Newest first", name: "newest", by: [{ field: "publishedAt", direction: "desc" }] },
    { title: "Price, low to high", name: "priceAsc", by: [{ field: "price", direction: "asc" }] },
  ],
  preview: {
    select: { title: "title", media: "images.0", price: "price", stock: "stock" },
    prepare({ title, media, price, stock }) {
      const status = stock === 0 ? " · Sold out" : typeof stock === "number" ? ` · ${stock} left` : "";
      return { title, media, subtitle: price ? `$${price}${status}` : "No price yet" };
    },
  },
});
