import { defineField, defineType } from "sanity";

export const siteSettings = defineType({
  name: "siteSettings",
  title: "Site settings",
  type: "document",
  groups: [
    { name: "general", title: "General", default: true },
    { name: "home", title: "Home page" },
    { name: "policies", title: "Promises" },
  ],
  fields: [
    defineField({
      name: "announcement",
      title: "Announcement bar",
      type: "string",
      group: "general",
      description: "The thin strip at the top of every page. Leave empty to hide it.",
    }),
    defineField({ name: "email", title: "Contact email", type: "string", group: "general" }),
    defineField({ name: "instagramUrl", title: "Instagram link", type: "url", group: "general" }),
    defineField({
      name: "whatsapp",
      title: "WhatsApp number (optional)",
      type: "string",
      group: "general",
      description: "International format, digits only, e.g. 15551234567",
    }),
    defineField({
      name: "etsyRating",
      title: "Etsy star rating",
      type: "number",
      group: "general",
      description: "Copy it from your Etsy shop page (e.g. 4.9). Leave empty to hide.",
      validation: (r) => r.min(1).max(5),
    }),
    defineField({
      name: "etsyReviewCount",
      title: "Number of Etsy reviews",
      type: "number",
      group: "general",
      validation: (r) => r.integer().min(0),
    }),
    defineField({ name: "heroTitle", title: "Headline", type: "string", group: "home" }),
    defineField({ name: "heroSubtitle", title: "Sub-headline", type: "text", rows: 2, group: "home" }),
    defineField({
      name: "heroImage",
      title: "Hero photo",
      type: "image",
      group: "home",
      description: "A wide, atmospheric photo. Landscape works best on desktop; the important part should sit in the centre.",
      options: { hotspot: true },
      fields: [defineField({ name: "alt", title: "Short description", type: "string" })],
    }),
    defineField({
      name: "heroVideo",
      title: "Hero video (optional)",
      type: "file",
      group: "home",
      description: "A short, silent, looping clip (10–20 s, under 15 MB). Plays behind the headline instead of the photo.",
      options: { accept: "video/mp4,video/quicktime,video/webm" },
    }),
    defineField({
      name: "freeShippingThreshold",
      title: "Free shipping over ($)",
      type: "number",
      group: "policies",
      description: "Set to 0 to hide free-shipping messages.",
      initialValue: 75,
    }),
    defineField({ name: "returnDays", title: "Return window (days)", type: "number", group: "policies", initialValue: 30 }),
    defineField({
      name: "shipsWithin",
      title: "Ships within",
      type: "string",
      group: "policies",
      initialValue: "1–2 business days",
    }),
  ],
  preview: { prepare: () => ({ title: "Site settings" }) },
});
